parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(DATABASE_URL): ''

# Doctrine Configuration
doctrine:
  dbal:
    # configure these for your database server
    driver:         'pdo_mysql'
    server_version: '8.0'
    charset:        utf8mb4
    types:
      phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType

    # With Symfony 3.3, remove the `resolve:` prefix
    url:            '%env(resolve:DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy:             doctrine.orm.naming_strategy.underscore
    auto_mapping:                true
    mappings:
      App\Security:
        is_bundle: false
        type:      xml
        dir:       '%kernel.project_dir%/config/doctrine/user'
        prefix:    'App\Security\Domain\Entity'
        alias:     App
      App\School:
        is_bundle: false
        type:      xml
        dir:       '%kernel.project_dir%/config/doctrine/school'
        prefix:    'App\School\Domain\Model'
        alias:     App\School
