framework:
    secret:          '%env(APP_SECRET)%'
    default_locale:  es
    csrf_protection: true
    http_method_override: true

    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_secure: auto
        cookie_samesite: lax

    #esi:             ~
    #fragments:       true
    php_errors:
        log: true

    profiler: { only_exceptions: false }

    validation:      { enable_annotations: true }
    trusted_hosts:   ~