# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    #encoders: ~

    encoders:
        App\Security\Domain\Entity\User:
            algorithm: auto

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            # Turn on anonymous for testings need.
            anonymous: true
            form_login:
                provider: app_user_provider
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                default_target_path: homepage
                always_use_default_target_path: true
                failure_path_parameter: /login
            #oauth:
            #    resource_owners:
            #        facebook:      "/login/check-facebook"
            #    login_path:        /login
            #    failure_path:      /login
            #    use_forward:       false
            #    oauth_user_provider:
            #        #service: hwi_oauth.user.provider.fosub_bridge
            #        service: App\Security\Core\User\FOSUBUserProvider
            logout:
                path: /logout
            guard:
                authenticators:
                    - App\Security\Domain\Authenticator\LoginFormAuthenticator

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: ROLE_USER }

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Security\Domain\Entity\User
                property: username
