fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Security\Domain\Entity\User
    use_username_form_type: false
    from_email:
        address: '%mail.from_address%'
        sender_name: '%mail.from_name%'
    registration:
        confirmation:
            enabled: true
    service:
      mailer: fos_user.mailer.noop
