stages:
    - test

cache:
    paths:
        - vendor/

test:
    tags:
        - docker
    stage: test
    script:
        - echo "Building the app"
        - docker-compose up -d
        - make composer-install
        - make cs-fix-dry-run
        - make phpunit
        - make phpspec
