pull_request_rules:
  - name: Automatic merge on dependabot requests
    conditions:
      - "author=dependabot-preview[bot]"
      - "base=master"
    actions:
      merge:
        method: merge
  - name: Automatic merge on mergify requests
    conditions:
      - "base=master"
      - check-success=PHPStan analysis
      - check-success=SonarCloud Code Analysis
      - check-success=Generate assets
      - check-success=codecov/project
      - "head~=^mergify/"
    actions:
      merge:
        method: merge
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
