version: '3.3'

services:
    nginx:
        image: "nginx:stable"
        restart: always
        links:
            - php
        depends_on:
            - php
            - mysql
        volumes:
            - .:/code
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        ports:
            - "8080:80"
    php:
        image: php:7.1-fpm
        restart: always
        links:
            - mysql
        depends_on:
            - mysql
        volumes:
            - .:/code
        networks:
            - code-network
        working_dir: /code
        environment:
            - XDEBUG_REMOTE_HOST=$DOCKER_HOST_IP
            - MYSQL_HOST=mysql
            - MYSQL_USER=dragoncity
            - MYSQL_DATABASE=danceschool
            - MYSQL_PASSWORD=danceschool
            - PHP_IDE_CONFIG=serverName=Docker
    composer:
        image: "composer"
        volumes:
            - ".:/code"
        command: install
    mysql:
        image: percona:latest
        restart: always
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_USER=danceschool
            - MYSQL_DATABASE=danceschool
            - MYSQL_PASSWORD=danceschool
            - MYSQL_ROOT_PASSWORD=danceschool

volumes:
    mysql_data:

networks:
    code-network:
        driver: bridge