version: '2'

services:
    nginx:
        image: "nginx:stable"
        restart: always
        links:
            - php
        depends_on:
            - php
        volumes:
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        networks:
            - code-network
        ports:
            - 8080:80
        networks:
            code-network:
                aliases:
                    - nginx
    php:
        image: php:7.1-fpm
        restart: always
        links:
            - mysql
        depends_on:
            - mysql
        volumes:
            - .:/code
        networks:
            - code-network
        working_dir: /code
        environment:
            - XDEBUG_REMOTE_HOST=$DOCKER_HOST_IP
            - MYSQL_HOST=mysql
            - MYSQL_USER=dragoncity
            - MYSQL_DATABASE=danceschool
            - MYSQL_PASSWORD=danceschool
            - PHP_IDE_CONFIG=serverName=Docker
        command: >
            --wait tcp://mysql:3306
               bash -c "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
        ports:
             - 9000:9000
        networks:
            code-network:
                aliases:
                    - php
    mysql:
        image: percona:latest
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            - MYSQL_USER=danceschool
            - MYSQL_DATABASE=danceschool
            - MYSQL_PASSWORD=danceschool
            - MYSQL_ROOT_PASSWORD=danceschool
        networks:
            code-network:
                aliases:
                    - mysql

volumes:
    mysql_data:

networks:
    code-network:
        driver: bridge