homepage:
    path:     /
    defaults: { _controller: App\School\UI\Http\Controller\DefaultController::index }

#_errors:
#    resource: "@TwigBundle/Resources/config/routing/errors.xml"
#    prefix:   /_error
