version: '3'

services:
  composer:
    image: "composer"
    volumes:
    - ../../:/code
    networks:
    - code-network
  nginx:
    image:   "nginx:stable"
    restart: always
    links:
    - php
    depends_on:
    - php
    - mysql
    volumes:
    - ../../:/code
    - ../../.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
    - code-network
    ports:
    - "8080:80"
  php:
    build:       .docker/php
    image:       zonadev/php:danceschool
    env_file:
    - ../../.env.docker
    restart:     always
    links:
    - mysql
    depends_on:
    - mysql
    volumes:
    - ../../:/code
    networks:
    - code-network
    ports:
    - "9001:9000"
    working_dir: /code
    environment:
    - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    - XDEBUG_REMOTE_HOST=192.168.99.1
    - XDEBUG_CONFIG="remote_host=192.168.99.1"
    - MYSQL_HOST=mysql
    - MYSQL_DATABASE=danceschool
    - MYSQL_USER=danceschool
    - MYSQL_PASSWORD=danceschool
    - PHP_IDE_CONFIG="serverName=app_docker"
  mysql:
    image:   percona:latest
    restart: always
    networks:
    - code-network
    ports:
    - "3307:3306"
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
    - MYSQL_USER=danceschool
    - MYSQL_DATABASE=danceschool
    - MYSQL_PASSWORD=danceschool
    - MYSQL_ROOT_PASSWORD=danceschool
  node:
    build:       .docker/nodejs
    image:       zonadev/nodejs:danceschool
    user:        "node"
    volumes:
    - ../../:/code
    networks:
    - code-network
    working_dir: /code
    ports:
    - "8081:8080"
    environment:
    - NODE_ENV=dev

volumes:
  mysql_data:

networks:
  code-network:
    driver: bridge
