version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo composer self-update
      - run: sudo composer install -n --no-scripts
      - run: make phpspec-unattended