version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.4-apache-node-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-cache-{{ checksum "composer.lock" }}
            - composer-cache-
      - run: sudo composer install -n --prefer-dist --no-scripts
      - save_cache:
          key: composer-cache-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: make cs-fix-dry-run
      - run: make phpspec-unattended
      - run: make phpunit
      - run: make autoload-check
