services:
    app.form.type.gender:
        class: App\Form\Type\GenderType
        arguments:
            - { form.gender.male: m, form.gender.female: f }
        tags:
            - { name: form.type, alias: gender }

    app.form.transformer.weekday:
        class: App\Form\DataTransformer\WeekdayTransformer

    app.form.type.weekday:
        class: App\Form\Type\WeekdayType
        arguments:
            - '@app.form.transformer.weekday'
        tags:
            - { name: form.type, alias: weekday }
