imports:
    - { resource: extra/forms_parameters.yml }

parameters:
    locale: es
    secret: b6b81bf786a28597d16ae47e47a56d87

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    mopa_bootstrap.form.render_optional_text: false
    mopa_bootstrap.form.render_required_asterisk: true
