monolog:
    handlers:
        main:
            #type:         fingers_crossed
            #action_level: error
            #handler:      nested

            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        nested:
            type:  stream
            path:  "php://stderr"
            level: error
        console:
            type:  console