parameters:
    database_driver: pdo_mysql
    database_host: mayimbe.zonadev.es
    database_port: null
    database_name: mayimbe
    database_user: mayimbe
    database_password: mayimbe

    assetic.filter.compass.bin: /app/vendor/bundle/bin/compass
    assetic.filter.less.node: /app/.heroku/node/bin/node
    assetic.filter.less.node_paths: [/app/node_modules]
    assetic.filter.sass.bin: /app/vendor/bundle/bin/sass
    assetic.filter.yui_css.timeout: 30
