# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: packages/forms_parameters.yaml }

parameters:
    locale: es
    secret: b6b81bf786a28597d16ae47e47a56d87

    database_driver: pdo_mysql
    database_host: mysql
    database_port: 3306
    database_name: danceschool
    database_user: danceschool
    database_password: danceschool

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    mail.from_address: admin@zonadev.es
    mail.from_name: ZonaDev

    assetic.filter.compass.bin: /usr/local/bin/compass
    assetic.filter.less.node: /usr/local/bin/node
    assetic.filter.less.node_paths: [/opt/lessc/lib, /usr/local/lib/node_modules]
    assetic.filter.sass.bin: /usr/local/bin/sass

    mopa_bootstrap.form.render_optional_text: false
    mopa_bootstrap.form.render_required_asterisk: true

    session.name: MSESSID

services:
    app_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        arguments: ['@fos_user.user_manager', {facebook: facebookId}]