services:
    app.form.type.gender:
        class: AppBundle\Form\Type\GenderType
        arguments:
            - { m: form.gender.male, f: form.gender.female }
        tags:
            - { name: form.type, alias: gender }