services:
    admin.course:
        class: AppBundle\Admin\CourseAdmin
        arguments: [~, AppBundle\Entity\Course, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Course }
        public: true

    admin.group:
        class: AppBundle\Admin\GroupAdmin
        arguments: [~, AppBundle\Entity\Group, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Group }
        public: true