services:
    admin.course:
        class: AppBundle\Admin\CourseAdmin
        arguments: [~, AppBundle\Entity\Course, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Course }
        public: true