# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: packages/forms_parameters.yaml }

parameters:
    locale: es
    secret: b6b81bf786a28597d16ae47e47a56d87

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    mail.from_address: admin@zonadev.es
    mail.from_name: ZonaDev

    mopa_bootstrap.form.render_optional_text: false
    mopa_bootstrap.form.render_required_asterisk: true

    session.name: MSESSID

services:
    app_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        arguments: ['@fos_user.user_manager', {facebook: facebookId}]