AppBundle\Entity\Course:
    type: entity
    table: `courses`
    fields:
        id:
            id: true
            type: integer
            length: 10
            unsigned: true
            generator:
                strategy: IDENTITY
        description:
            type: text
            nullable: true
        price:
            type: float
            nullable: false
    oneToMany:
        group:
            targetEntity: AppBundle\Entity\Group
            mappedBy: course
