AppBundle\Entity\Course:
    type: entity
    table: courses
    repositoryClass: AppBundle\Repository\CourseRepository
    fields:
        id:
            id: true
            type: integer
            length: 10
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        description:
            type: text
            nullable: true
            length: null
            fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
    oneToMany:
        groups:
            targetEntity: AppBundle\Entity\Group
            mappedBy: course
    lifecycleCallbacks: {  }
