AppBundle\Entity\GroupStudent:
    type: entity
    table: group_students
    id:
        group:
            associationKey: true
        student:
            associationKey: true
    fields:
        is_reinforcing:
            type: boolean
            nullable: false
            default: 0
    manyToOne:
        group:
            id: true
            targetEntity: AppBundle\Entity\Group
            inversedBy: groupStudent
            joinColumn:
                name: group_id
                referencedColumnName: id
            nullable: false
        student:
            id: true
            targetEntity: AppBundle\Entity\Student
            inversedBy: groupStudent
            joinColumn:
                name: student_id
                referencedColumnName: id
            nullable: false
