AppBundle\Entity\Group:
    type: entity
    table: groups
    indexes:
        idx_group_course:
            columns:
                - course_id
        idx_group_room:
            columns:
                - room_id
        idx_group_teacher:
            columns:
                - teacher_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 50
            nullable: false
            fixed: false
        weekday:
            type: smallint
            nullable: true
            unsigned: false
        hour:
            type: time
            nullable: false
        startDate:
            type: date
            nullable: false
            column: start_date
            columnDefinition: DATE
        endDate:
            type: date
            nullable: false
            column: end_date
            columnDefinition: DATE
        whatsappGroup:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: whatsapp_group
    manyToOne:
        course:
            targetEntity: AppBundle\Entity\Course
            inversedBy: groups
            cascade: {  }
            mappedBy: null
            joinColumn:
                course_id:
                    referencedColumnName: id
            nullable: false
            orphanRemoval: false
        room:
            targetEntity: AppBundle\Entity\Room
            cascade: {  }
            mappedBy: null
            joinColumn:
                room_id:
                    referencedColumnName: id
            nullable: false
            orphanRemoval: false
        teacher:
            targetEntity: AppBundle\Entity\Teacher
            inversedBy: groups
            cascade: {  }
            mappedBy: null
            joinColumn:
                teacher_id:
                    referencedColumnName: id
            nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }

    oneToMany:
        groupStudent:
            targetEntity: AppBundle\Entity\GroupStudent
            mappedBy: group