AppBundle\Entity\GroupStudent:
    type: entity
    table: group_students
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        is_reinforcing:
            type: boolean
            nullable: true
            options:
                default: false
    manyToOne:
        group:
            id: true
            targetEntity: AppBundle\Entity\Group
            inversedBy: groupStudent
            joinColumn:
                name: group_id
                referencedColumnName: id
            nullable: false
        student:
            id: true
            targetEntity: AppBundle\Entity\Student
            inversedBy: groupStudent
            joinColumn:
                name: student_id
                referencedColumnName: id
            nullable: false
