Groups:
    type: entity
    table: groups
    indexes:
        IDX_F06D3970591CC992:
            columns:
                - course_id
        IDX_F06D397054177093:
            columns:
                - room_id
        IDX_F06D397041807E1D:
            columns:
                - teacher_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        weekday:
            type: smallint
            nullable: true
            unsigned: false
        hour:
            type: time
            nullable: false
        startDate:
            type: date
            nullable: false
            column: start_date
        endDate:
            type: date
            nullable: false
            column: end_date
        whatsappGroup:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: whatsapp_group
    manyToOne:
        teacher:
            targetEntity: Teachers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                teacher_id:
                    referencedColumnName: id
            orphanRemoval: false
        room:
            targetEntity: Rooms
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                room_id:
                    referencedColumnName: id
            orphanRemoval: false
        course:
            targetEntity: Courses
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                course_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        student:
            targetEntity: Students
            cascade: {  }
            mappedBy: null
            inversedBy: group
            joinTable:
                name: group_students
                joinColumns:
                    -
                        name: group_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: student_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
