AppBundle\Entity\Room:
    type: entity
    table: rooms
    id:
        id:
            id: true
            type: integer
            nullable: false
            unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 50
            nullable: false
        description:
            type: text
            nullable: true
            length: null
            fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        address:
            type: text
            nullable: true
            options:
                default: null
        city:
            type: string
            length: 15
            nullable: true
            options:
                default: null
        postalCode:
            type: string
            nullable: true
            length: 15
            fixed: false
            column: postal_code
            options:
                default: null
        phone:
            #type: phone_number
            type: phone_number
            nullable: true

    oneToMany:
        group:
            targetEntity: AppBundle\Entity\Group
            mappedBy: room
    lifecycleCallbacks: {  }