Students:
    type: entity
    table: students
    uniqueConstraints:
        UNIQ_A4698DB2A76ED395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        captationMethod:
            type: smallint
            nullable: true
            unsigned: false
            column: captation_method
        member:
            type: boolean
            nullable: true
            default: '0'
        contractExpiration:
            type: date
            nullable: true
            column: contract_expiration
        comment:
            type: text
            nullable: true
            length: null
            fixed: false
        accountNumber:
            type: string
            nullable: true
            length: 255
            fixed: false
            default: ''
            column: account_number
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        group:
            targetEntity: Groups
            cascade: {  }
            mappedBy: student
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
