StudentAnnotations:
    type: entity
    table: student_annotations
    indexes:
        IDX_9F731506CB944F1A:
            columns:
                - student_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        message:
            type: text
            nullable: false
            length: null
            fixed: false
        created:
            type: datetime
            nullable: false
        modified:
            type: datetime
            nullable: false
    manyToOne:
        student:
            targetEntity: Students
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                student_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
