AppBundle\Entity\Teacher:
    type: entity
    table: teachers
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        wage:
            type: float
            nullable: false
            precision: 10
            scale: 0
            default: 0
        comment:
            type: text
            nullable: true
            length: null
            fixed: false
    oneToOne:
        user:
            targetEntity: AppBundle\Entity\User
            cascade: ["persist"]
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: "cascade"
#    manyToMany:
#        groups:
#            targetEntity: AppBundle\Entity\Group
#            cascade: {  }
#            mappedBy: teacher
#            inversedBy: group
#            joinTable:
#                name: group_teachers
#                joinColumns:
#                    -
#                        name: group_id
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    -
#                        name: teacher_id
#                        referencedColumnName: id
#            orderBy: null

    oneToMany:
        group:
            targetEntity: AppBundle\Entity\Group
            mappedBy: teacher