Teachers:
    type: entity
    table: teachers
    uniqueConstraints:
        UNIQ_ED071FF6A76ED395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        wage:
            type: float
            nullable: true
            precision: 10
            scale: 0
        comment:
            type: text
            nullable: true
            length: null
            fixed: false
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
