AppBundle\Entity\Teacher:
    type: entity
    table: teachers
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        wage:
            type: float
            nullable: true
            precision: 10
            scale: 0
        comment:
            type: text
            nullable: true
            length: null
            fixed: false
    oneToOne:
        user:
            targetEntity: AppBundle\Entity\User
            cascade: ["persist"]
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: "cascade"
    oneToMany:
        groups:
            targetEntity: AppBundle\Entity\Group
            mappedBy: teacher