AppBundle\Entity\User:
    type: entity
    table: users
    lifecycleCallbacks:
        prePersist: [setCreatedAt, setUpdatedAt]
        preUpdate: [setUpdatedAt]
    uniqueConstraints:
        UNIQ_1483A5E992FC23A8:
            columns:
                - username_canonical
        UNIQ_1483A5E9A0D96FBF:
            columns:
                - email_canonical
        UNIQ_1483A5E92BC7B602:
            columns:
                - identity_number
    id:
        id:
            id: true
            type: integer
            length: 10
            unsigned: true
            generator:
                strategy: IDENTITY
    attributeOverride:
        salt:
             type: string
             nullable: true
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        surname:
            type: string
            nullable: true
            length: 255
            fixed: false
            default: null
        gender:
            type: string
            nullable: true
            length: 1
            fixed: false
            comment: 'm: Male, f: female'
        birthday:
            type: date
            nullable: true
            columnDefinition: DATE
        phone:
            type: string
            nullable: true
            length: 30
            fixed: false
        address:
            type: string
            nullable: true
            length: 255
            fixed: false
        city:
            type: string
            nullable: true
            length: 45
            fixed: false
        country:
            type: string
            nullable: true
            length: 2
            fixed: false
            default: ES
            options:
                default: "ES"
                comment: "Use ISO Code"
        postalCode:
            type: string
            nullable: true
            length: 15
            fixed: false
            column: postal_code
        identityNumber:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: identity_number
        created:
            type: datetime
            nullable: false
        modified:
            type: datetime
            nullable: false
#        expired:
#            type: boolean
#            nullable: false
#        expiresAt:
#            type: datetime
#            nullable: true
#            column: expires_at
#        credentialsExpired:
#            type: boolean
#            nullable: false
#            column: credentials_expired
#        credentialsExpireAt:
#            type: datetime
#            nullable: true
#            column: credentials_expire_at
