App\Entity\Course:
    type: entity
    table: courses
    repositoryClass: App\Repository\CourseRepository
    fields:
        id:
            id: true
            type: integer
            length: 10
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 20
            nullable: true
            fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
    oneToMany:
        groups:
            targetEntity: App\Entity\Group
            mappedBy: course
    lifecycleCallbacks: {  }
