App\Entity\StudentAnnotation:
    type: entity
    table: student_annotations
    lifecycleCallbacks:
        prePersist: [setCreatedAt, setUpdatedAt]
        preUpdate: [setUpdatedAt]
    indexes:
        idx_student_anotation_student_id:
            columns:
                - student_id
    id:
        id:
            id: true
            type: integer
            nullable: false
            unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        message:
            type: text
            nullable: false
        created:
            type: datetime
            nullable: false
        modified:
            type: datetime
            nullable: false
    manyToOne:
        student:
            targetEntity: App\Entity\Student
            inversedBy: annotations
            joinColumn:
                student_id:
                    referencedColumnName: id
                    nullable: false
            orphanRemoval: false