parameters:
    assetic.filter.compass.bin: /app/vendor/bundle/bin/compass
    assetic.filter.less.node: /app/.heroku/node/bin/node
    assetic.filter.less.node_paths: [/app/node_modules]
    assetic.filter.sass.bin: /usr/local/bin/sass