name: Codecov

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  run:
    name: Code Coverage Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        env:
          PACKAGES: ${{ secrets.PACKAGES }}
        run:  |
          make docker-login
          make up-ci
          make composer-install
      - name: Run Coverage
        run:  |
          make test-coverage-codecov
      - name: Upload coverage to Codecov
        env:
          TOKEN: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
        uses: codecov/codecov-action@v1.5.0
        with:
          token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
          file: ./build/codecov/phpunit.xml
          flags: phpunit
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
      - name: Upload coverage to Codecov
        env:
          TOKEN: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
        uses: codecov/codecov-action@v1.5.0
        with:
          token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
          file: ./build/coverage/phpspec.xml
          flags: phpspec
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
