name: Codecov

on:
  push:
    branches:
    - master
    - task/addActions

jobs:
  analyze:
    name:    PHP Code Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the stack
      run:  |
            make up-ci
    - name: Run Coverage
      run:  |
            make test-coverage-codecov
    - name: Send Coverage
      env:
        TOKEN: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
      run:  |
            bash <(curl -s https://codecov.io/bash) -t ${TOKEN} -s build/codecov/
