name: Generate Assets

on:
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Generate assets
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '15.x'
    #- run: yarn add sass-loader node-sass@4.14.1 --dev
    - run: yarn install
    - run: yarn run encore dev

