name: PHPStan static analysis

on:   pull_request

jobs:
  analyze:
    name: PHPStan analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install vendors
      run:  |
            composer --no-scripts --prefer-dist --no-interaction --ignore-platform-reqs install
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
    - name: Prepare PHPStan source
      env:
        BUILD_FOLDER: /tmp/build/phpstan
        CACHE_FILE:   ${BUILD_FOLDER}/phpstan.result.cache
      run:  |
            mkdir -p /tmp/build/phpstan
            vendor/bin/phpstan analyse --memory-limit=-1 -l max -c ${PWD}/etc/phpstan/phpstan.neon --no-progress --no-interaction src > /tmp/build/phpstan/phpstan.result.cache >/dev/null 2>&1 || true
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Run PHPStan Analysis
      run:  |
            ${PWD}/bin/phpstan-analysis.sh
