name: Publish Docker image
on:
  push:
    branches: master
jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: etc/docker/.docker/php
          file: etc/docker/.docker/php/Dockerfile
          platforms: linux/386
          push: true
          cache-from: type=registry,ref=jacanales/danceschool/php:7.4
          cache-to: type=inline
          tags: |
            docker.pkg.github.com/jacanales/danceschool/php:7.4
